//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MammacookedWebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string About { get; set; }
        public string BreakFastAddr { get; set; }
        public string LunchAddr { get; set; }
        public string Dinner { get; set; }
        public string B_LatLong { get; set; }
        public string L_LatLong { get; set; }
        public string D_latLong { get; set; }
        public bool Verified { get; set; }
        public bool ValidForSupply { get; set; }
        public decimal MonyBalance { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public bool DeleteFlag { get; set; }
        public string ImagePath { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
    }
}
