//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MammacookedWebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems1 = new HashSet<OrderItem1>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TimeSlot { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentMedium { get; set; }
        public string DeleveredTo { get; set; }
        public Nullable<double> PendingAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem1> OrderItems1 { get; set; }
    }
}
