//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MammacookedWebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem1
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Quantity { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual Order Order { get; set; }
    }
}
